apiVersion: v2
version: 0.4.1
appVersion: v1.7.0
description: 'Cortex'
engine: gotpl
home: https://cortexmetrics.io/
icon: https://avatars2.githubusercontent.com/u/43045022?s=200&v=4
kubeVersion: ^1.10.0-0
maintainers:
  - email: cortex-team@googlegroups.com
    name: Cortex Maintainers
name: cortex
sources:
  - https://github.com/cortexproject/cortex-helm-chart
dependencies:
  - name: memcached
    alias: memcached
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled
  - name: memcached
    alias: memcached-index-read
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-index-read.enabled
  - name: memcached
    alias: memcached-index-write
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-index-write.enabled
  - name: memcached
    alias: memcached-frontend
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-frontend.enabled
  - name: memcached
    alias: memcached-blocks-index
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - blocks-storage-memcached
  - name: memcached
    alias: memcached-blocks
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - blocks-storage-memcached
  - name: memcached
    alias: memcached-blocks-metadata
    version: 5.5.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - blocks-storage-memcached
